import fs from 'fs/promises';
import path from 'path';

export class DigestSaver {
  constructor(config) {
    this.config = config;
    this.outputDir = config.localSaving?.outputDirectory || 'digests';
  }

  async saveDigest(summary, metadata, costReport, postsCount) {
    if (!this.config.localSaving?.enabled) {
      console.log('ℹ️  Local digest saving is disabled');
      return;
    }

    try {
      // Ensure output directory exists
      await fs.mkdir(this.outputDir, { recursive: true });

      const date = new Date();
      const dateString = date.toISOString().split('T')[0]; // YYYY-MM-DD format
      const timeString = date.toTimeString().split(' ')[0].replace(/:/g, '-'); // HH-MM-SS format
      
      const filename = `bluesky-digest-${dateString}-${timeString}.md`;
      const filepath = path.join(this.outputDir, filename);

      const markdownContent = this.generateMarkdown(summary, metadata, costReport, postsCount, date);
      
      await fs.writeFile(filepath, markdownContent, 'utf-8');
      
      console.log(`✓ Digest saved locally to: ${filepath}`);
      return filepath;
    } catch (error) {
      console.error('✗ Failed to save digest locally:', error.message);
      throw error;
    }
  }

  generateMarkdown(summary, metadata, costReport, postsCount, date) {
    const dateString = date.toLocaleDateString('en-US', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    let markdown = `# 🦋 Bluesky Daily Digest\n\n`;
    markdown += `**Date:** ${dateString}\n\n`;
    markdown += `**Generated:** ${date.toLocaleString()}\n\n`;

    if (this.config.localSaving?.includeMetadata) {
      markdown += `## 📊 Summary Statistics\n\n`;
      markdown += `- **Posts Analyzed:** ${postsCount}\n`;
      markdown += `- **AI Model:** ${metadata.model}\n`;
      markdown += `- **Tokens Used:** ${metadata.inputTokens.toLocaleString()} input, ${metadata.outputTokens.toLocaleString()} output\n`;
      markdown += `- **Generation Cost:** $${metadata.cost.toFixed(4)}\n`;
      markdown += `- **Total Session Cost:** $${costReport.totalCost.toFixed(4)}\n`;
      markdown += `- **Budget Remaining:** $${(this.config.dailyCostBudget - costReport.totalCost).toFixed(4)}\n\n`;
    }

    markdown += `## 📝 Daily Summary\n\n`;
    markdown += summary;

    markdown += `\n\n---\n\n`;
    markdown += `*Generated by Bluesky Daily Digest v2 on ${date.toISOString()}*\n`;

    return markdown;
  }

  async listSavedDigests() {
    try {
      const files = await fs.readdir(this.outputDir);
      const digestFiles = files
        .filter(file => file.startsWith('bluesky-digest-') && file.endsWith('.md'))
        .sort()
        .reverse(); // Most recent first

      return digestFiles.map(file => ({
        filename: file,
        path: path.join(this.outputDir, file),
        date: this.extractDateFromFilename(file)
      }));
    } catch (error) {
      console.error('Error listing saved digests:', error.message);
      return [];
    }
  }

  extractDateFromFilename(filename) {
    const match = filename.match(/bluesky-digest-(\d{4}-\d{2}-\d{2})-(\d{2}-\d{2}-\d{2})\.md/);
    if (match) {
      const [, datePart, timePart] = match;
      const timeFormatted = timePart.replace(/-/g, ':');
      return new Date(`${datePart}T${timeFormatted}`);
    }
    return null;
  }

  async getRecentDigests(count = 5) {
    const digests = await this.listSavedDigests();
    return digests.slice(0, count);
  }
}