import sgMail from '@sendgrid/mail';

export class EmailSender {
  constructor(apiKey, fromEmail) {
    sgMail.setApiKey(apiKey);
    this.fromEmail = fromEmail;
  }

  async send(recipients, subject, htmlContent, textContent, costReport) {
    try {
      console.log(`Sending email to ${recipients.length} recipient(s)...`);

      const msg = {
        to: recipients,
        from: this.fromEmail,
        subject: subject,
        text: textContent,
        html: this.buildHtmlEmail(htmlContent, costReport)
      };

      await sgMail.sendMultiple(msg);
      console.log('✓ Email sent successfully');
    } catch (error) {
      console.error('✗ Email sending failed:', error.message);
      if (error.response) {
        console.error('Response body:', error.response.body);
      }
      throw error;
    }
  }

  buildHtmlEmail(summary, costReport) {
    return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 10px;
      margin-bottom: 30px;
    }
    .header h1 {
      margin: 0;
      font-size: 28px;
    }
    .header p {
      margin: 10px 0 0 0;
      opacity: 0.9;
    }
    .content {
      background: #f8f9fa;
      padding: 30px;
      border-radius: 10px;
      margin-bottom: 20px;
    }
    .footer {
      text-align: center;
      padding: 20px;
      color: #666;
      font-size: 12px;
      border-top: 1px solid #ddd;
      margin-top: 30px;
    }
    .cost-badge {
      display: inline-block;
      background: #10b981;
      color: white;
      padding: 5px 15px;
      border-radius: 20px;
      font-size: 14px;
      margin-top: 10px;
    }
    pre {
      background: white;
      padding: 15px;
      border-radius: 5px;
      overflow-x: auto;
      white-space: pre-wrap;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🦋 Your Daily Bluesky Digest</h1>
    <p>${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
    <span class="cost-badge">Cost: $${costReport.totalCost.toFixed(4)}</span>
  </div>
  
  <div class="content">
    <pre>${summary}</pre>
  </div>
  
  <div class="footer">
    <p>Generated by Bluesky Daily Digest | OpenAI API Calls: ${costReport.requestCount} | Total Cost: $${costReport.totalCost.toFixed(4)}</p>
    <p style="margin-top: 10px;">
      <a href="https://github.com/yourusername/bluesky-daily-digest" style="color: #667eea; text-decoration: none;">View on GitHub</a>
    </p>
  </div>
</body>
</html>
    `;
  }
}
